### ISSUE TITLE
NUI版本又加回了JOIN ROOM的按钮. 上周试了一下是好用的. 近期准备花时间重新适配一波这个摄像头脚本.

### ISSUE THREAD

**Issue by honeyeyo** [honeyeyo/PrivateCamera#1]

**Comment by honeyeyo** [comment]
2024-09-25 01:16:15 
今天抽空简单改完了log_parser的逻辑， 能够判断进出房间的时机了。
明天有空的话把joinroom exitroom的逻辑重新适配一下NUI。大概就可以恢复使用了

**Comment by honeyeyo** [comment]
今天把脚本调试差不多了，基本逻辑都能用了， 不过连续多次进入房间的时候，还有个排位的弹窗没有关掉。明天再调试一下应该就OK了。 另外重新写个使用说明。
![Uploading 微信截图_20240929004756.png…]()

**Comment by ddoott0930** [comment]
使用说明“没有访问权限”~~~~

**Comment by honeyeyo** [comment]
> 使用说明“没有访问权限”~~~~

已打开。再试试呢

**Comment by ddoott0930** [comment]
o了~我来帮你测试一下ocu版本和steam版本~
