### ISSUE TITLE
请问steam版能用这个吗？

### ISSUE THREAD

**Issue by ddoott0930** [honeyeyo/PrivateCamera#2]
Eleven.exe在steam版里面叫pong_waves_vr.exe是不是要换名字覆盖

**Comment by ddoott0930** [comment]
试了一下oculus的pc版但是没有成功，对了几遍流程也确认改了用户名、桌面路径，运行之后画面跳到了一个很顶部的视角然后就没有其他动作了

**Comment by honeyeyo** [comment]
目前最新版的python脚本不依赖于dll注入，应该是可以用了

**Comment by ddoott0930** [comment]
Steam版的2d视角逻辑好像不太一样，感觉不能用
是有一根线指示视角而不是直接移动画面变化视角
